logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
---
server:
  port: 8080
  servlet:
    context-path: /baseServices
---
keycloak:
  enabled: true
  bearer-only: true
  auth-server-url: https://lemur-18.cloud-iam.com/auth
  resource: ENTERPRISE-WS
  realm: auth1
  public-client: true
  principal-attribute: preferred_username
  # credentials:
  # secret: 123
  use-resource-role-mappings: false
  allowAnyHostname: true
  ssl-required: external
---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sicpa
    username: postgres
    password: admin
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      connectionTestQuery: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        dialect: org.hibernate.dialect.MariaDB103Dialect

springdoc:
  springdoc:
    packagesToScan: com.base.controller
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    enabled: true
    disable-swagger-default-url: true