logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR
---
server:
  port: 8080
  servlet:
    context-path: /baseServices
---
springdoc:
  swagger-ui:
    disable-swagger-default-url: true